//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Add_Spare_Part
    {
        public long SPAREPART_ID { get; set; }
        public Nullable<long> SERVICE_CALL_ID { get; set; }
        public Nullable<long> SP_ID { get; set; }
        public Nullable<long> QUANTITY { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    }
}
