//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_AdminPermission
    {
        public long P_ID { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public string Customer_Master { get; set; }
        public string Regular_Customer { get; set; }
        public string AERB_Customer { get; set; }
        public string Medtronic_Customer { get; set; }
        public string Mindray_Customer { get; set; }
        public string Customer_Service { get; set; }
        public string Service_Call_Assign { get; set; }
        public string Regular { get; set; }
        public string AERB { get; set; }
        public string Medtronic { get; set; }
        public string Mindray { get; set; }
        public string Sales_Lead { get; set; }
        public string Regular_Product_Master { get; set; }
        public string Category { get; set; }
        public string Manufacturer { get; set; }
        public string Regular_Product { get; set; }
        public string Spare_Part { get; set; }
        public string URD_Product_Purchase { get; set; }
        public string Standard_Accessories { get; set; }
        public string Mindray_Product_Master { get; set; }
        public string Mindray_Product { get; set; }
        public string Probe_Specifications { get; set; }
        public string Medtronic_Products_List { get; set; }
        public string Medtronic_Product { get; set; }
        public string Main_System { get; set; }
        public string Attachments { get; set; }
        public string Tools { get; set; }
        public string Incentive { get; set; }
        public string Incentive_Master { get; set; }
        public string Incentive_Scheme { get; set; }
        public string Quotation_Master { get; set; }
        public string Regular_Quotation { get; set; }
        public string AERB_Quotation { get; set; }
        public string Medtronic_Quotation { get; set; }
        public string Mindray_Quotation { get; set; }
        public string Report_Master { get; set; }
        public string Attendance_Report { get; set; }
        public string Leave_Report { get; set; }
        public string Monthly_Salary_Report { get; set; }
        public string Daily_Activity { get; set; }
        public string Delivery_Challan { get; set; }
        public string Regular_DC { get; set; }
        public string AERB_DC { get; set; }
        public string Medtronic_DC { get; set; }
        public string Mindray_DC { get; set; }
        public string AMC_CMC_Master { get; set; }
        public string AMC_CMC_Regular { get; set; }
        public string AMC_CMC_AERB { get; set; }
        public string AMC_CMC_Medtronic { get; set; }
        public string AMC_CMC_Mindray { get; set; }
        public string Payment_Receipt { get; set; }
        public string Payment_Receipt_Regular { get; set; }
        public string Payment_Receipt_AERB { get; set; }
        public string Payment_Receipt_Medtronic { get; set; }
        public string Payment_Receipt_Mindray { get; set; }
        public string Salary_Wages { get; set; }
        public string Salary_Increment { get; set; }
        public string Advance_Salary { get; set; }
        public string Employee_Loan { get; set; }
        public string Setting { get; set; }
        public string Company_Master { get; set; }
        public string Employee_Registration { get; set; }
        public string Department_Master { get; set; }
        public string Designation_Master { get; set; }
        public string Vender_Registration { get; set; }
        public string Solution_Bank { get; set; }
        public string City_Master { get; set; }
        public string Invoice_Master { get; set; }
        public string Invoice_Regular { get; set; }
        public string Invoice_AERB { get; set; }
        public string Invoice_Medtronic { get; set; }
        public string Invoice_Mindray { get; set; }
        public string Vendor_PO_Master { get; set; }
        public string Vendor_PO_Regular { get; set; }
        public string Vendor_PO_AERB { get; set; }
        public string Vendor_PO_Medtronic { get; set; }
        public string Vendor_PO_Mindray { get; set; }
        public string Employee_Expense_Master { get; set; }
    }
}
