//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Banner
    {
        public long BANNER_ID { get; set; }
        public string BANNER_NAME { get; set; }
        public string BANNER_LINK { get; set; }
        public string BANNER_IMAGE { get; set; }
        public string STATUS { get; set; }
        public Nullable<long> ADMIN_ID { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    }
}
