//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CompanyMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_CompanyMaster()
        {
            this.TB_Company_DocumentMaster = new HashSet<TB_Company_DocumentMaster>();
            this.TB_CompanyBankMaster = new HashSet<TB_CompanyBankMaster>();
            this.TB_Vendor_PO_Master = new HashSet<TB_Vendor_PO_Master>();
        }
    
        public long COMPANY_ID { get; set; }
        public string COMPANY_NAME { get; set; }
        public string COMPANY_REG_ADDRESS { get; set; }
        public string COMPANY_COR_ADDRESS { get; set; }
        public string ZIP_CODE { get; set; }
        public string AUTHORITY_NAME { get; set; }
        public string MOBILE_NO { get; set; }
        public string ALT_MOBILE_NO { get; set; }
        public string SERVICES { get; set; }
        public string COMPANY_TYPE { get; set; }
        public string COMPANY_REG { get; set; }
        public string EMAIL_ID { get; set; }
        public string PNDT_NO { get; set; }
        public string CST_NO { get; set; }
        public string PAN_NO { get; set; }
        public string VAT_TIN_NO { get; set; }
        public string GST_NO { get; set; }
        public string BANK_NAME { get; set; }
        public string IFSC_CODE { get; set; }
        public string ACC_NO { get; set; }
        public string ACC_HOLDER_NAME { get; set; }
        public string BRANCH_NAME { get; set; }
        public string COMPANY_LOGO { get; set; }
        public string COMPANY_LETTERHEAD { get; set; }
        public string COMPANY_SEAL { get; set; }
        public string SIGNATURE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string PASSWORD { get; set; }
        public string LOGIN_TYPE { get; set; }
        public string TIN_NO { get; set; }
        public string COMPANY_PNDT_CERTIFICATE { get; set; }
        public string COMPANY_PREFIX { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Company_DocumentMaster> TB_Company_DocumentMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_CompanyBankMaster> TB_CompanyBankMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Vendor_PO_Master> TB_Vendor_PO_Master { get; set; }
    }
}
