//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_CustomerMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_CustomerMaster()
        {
            this.Tb_AMC_CMC_Master = new HashSet<Tb_AMC_CMC_Master>();
            this.TB_DeliveryChallan = new HashSet<TB_DeliveryChallan>();
            this.Tb_FirmMaster = new HashSet<Tb_FirmMaster>();
            this.TB_ServiceCall = new HashSet<TB_ServiceCall>();
            this.TB_InvoiceMaster = new HashSet<TB_InvoiceMaster>();
            this.TB_InvoiceMaster1 = new HashSet<TB_InvoiceMaster>();
            this.TB_SparePartStock = new HashSet<TB_SparePartStock>();
            this.TB_ProductStockMaster = new HashSet<TB_ProductStockMaster>();
            this.TB_ProductStockMaster1 = new HashSet<TB_ProductStockMaster>();
        }
    
        public long Customer_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string FIRM_NAME { get; set; }
        public string CONTACT_NO { get; set; }
        public string ALTERNATE_CONTACT_NO { get; set; }
        public string EMAIL { get; set; }
        public string ALTERNATE_EMAIL { get; set; }
        public string BILLING_ADDRESS { get; set; }
        public string SHIPPING_ADDRESS { get; set; }
        public Nullable<long> STATE_ID { get; set; }
        public Nullable<long> CITY_ID { get; set; }
        public string ZIP_CODE { get; set; }
        public string DEGREE_OF_CUSTOMER { get; set; }
        public string PAN_NO { get; set; }
        public string GST_NO { get; set; }
        public string TIN_NO { get; set; }
        public string PNDT_NO { get; set; }
        public Nullable<System.DateTime> PNDT_VALIDITY { get; set; }
        public string UPLOAD_PNDT_CERTIFICATE { get; set; }
        public string UPLOAD_PAN_CERTIFICATE { get; set; }
        public string ADDRESS { get; set; }
        public string UNIT { get; set; }
        public string ADD_EQUIPMENT { get; set; }
        public string ELORA_USER_ID { get; set; }
        public string ELORA_PASSWORD { get; set; }
        public string NO_OF_TLD { get; set; }
        public string DOCUMENT_STATUS { get; set; }
        public string REGISTRATION_STATUS { get; set; }
        public string REPORT_STATUS { get; set; }
        public string TOTAL_AMOUNT { get; set; }
        public string BALANCE_PAYMENT { get; set; }
        public string CHEQUE_NO { get; set; }
        public string QA_DONE_BY { get; set; }
        public Nullable<System.DateTime> QA_DONE_ON_DATE { get; set; }
        public string QA_SALE_PERSON { get; set; }
        public Nullable<System.DateTime> QA_DUE_DATE { get; set; }
        public string QA_PERSON_COMMISSON { get; set; }
        public string UPLOD_DOCUMETN { get; set; }
        public string COMMENT { get; set; }
        public string BRANCH_NAME { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public string SHIPPING_ZIP_CODE { get; set; }
        public Nullable<long> SHIP_STATE_ID { get; set; }
        public Nullable<long> SHIP_CITY_ID { get; set; }
        public Nullable<long> CUSTOMER_TYPE_ID { get; set; }
        public string CITY_NAME_DELETE { get; set; }
        public string STATE_NAME_DELETE { get; set; }
        public string CUST_CODE_DELETE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_AMC_CMC_Master> Tb_AMC_CMC_Master { get; set; }
        public virtual Tb_CustomerType Tb_CustomerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DeliveryChallan> TB_DeliveryChallan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_FirmMaster> Tb_FirmMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ServiceCall> TB_ServiceCall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_InvoiceMaster> TB_InvoiceMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_InvoiceMaster> TB_InvoiceMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SparePartStock> TB_SparePartStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ProductStockMaster> TB_ProductStockMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ProductStockMaster> TB_ProductStockMaster1 { get; set; }
    }
}
