//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CallPriorityType
    {
        public byte CALL_PRIORITY_TYPE_ID { get; set; }
        public string CALL_PRIORITY_TYPE_NAME { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
