//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CHECKIN
    {
        public long CHECKIN_ID { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public string CHECK_IN_TYPE { get; set; }
        public Nullable<long> VEHICAL_TYPE_ID { get; set; }
        public string ODOMETER_PHOTO_CHECK_IN { get; set; }
        public string ODOMETER_PHOTO_CHECK_OUT { get; set; }
        public Nullable<System.DateTime> CHECK_IN_TIME { get; set; }
        public Nullable<System.DateTime> CHECK_OUT_TIME { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string CHECK_IN_STATUS { get; set; }
        public string CHECK_IN_LATITUDE { get; set; }
        public string CHECK_IN_LONGITUDE { get; set; }
        public string CHECK_OUT_LATITUDE { get; set; }
        public string CHECK_OUT_LONGITUDE { get; set; }
    }
}
