//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DeliveryChallan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_DeliveryChallan()
        {
            this.TB_DC_Accessories = new HashSet<TB_DC_Accessories>();
            this.TB_DC_SparePart = new HashSet<TB_DC_SparePart>();
            this.TB_DC_MedtronicAccessories = new HashSet<TB_DC_MedtronicAccessories>();
        }
    
        public int DC_ID { get; set; }
        public string DC_NUMBER { get; set; }
        public Nullable<long> Customer_ID { get; set; }
        public Nullable<System.DateTime> DC_DATE { get; set; }
        public Nullable<long> P_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<bool> IS_DC_FOR_SPAREPARTS { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<bool> INC_ALL_TAXES { get; set; }
        public Nullable<byte> GST { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<decimal> AMOUNT_INC_TAX { get; set; }
        public Nullable<int> MATERIAL_ID { get; set; }
        public Nullable<System.DateTime> DC_CLOSE_DATE { get; set; }
        public Nullable<int> DCS_ID { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<long> F_ID { get; set; }
        public string CHALLAN_IMAGE { get; set; }
        public string ADMIN_REMARK { get; set; }
        public Nullable<long> CHALLAN_UPLOADED_BY_ADMIN { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
    
        public virtual Tb_CustomerMaster Tb_CustomerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DC_Accessories> TB_DC_Accessories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DC_SparePart> TB_DC_SparePart { get; set; }
        public virtual TB_DCStatus TB_DCStatus { get; set; }
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
        public virtual TB_Material TB_Material { get; set; }
        public virtual Tb_FirmMaster Tb_FirmMaster { get; set; }
        public virtual Tb_Product Tb_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DC_MedtronicAccessories> TB_DC_MedtronicAccessories { get; set; }
    }
}
