//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EmployeeLoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_EmployeeLoan()
        {
            this.TB_EmployeeSalary = new HashSet<TB_EmployeeSalary>();
        }
    
        public long EMP_LOAN_ID { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public Nullable<decimal> LOAN_AMOUNT { get; set; }
        public Nullable<decimal> INTREST_RATE { get; set; }
        public Nullable<decimal> INSTALLMENT_AMOUNT { get; set; }
        public Nullable<decimal> LOAN_OUTSTANDING { get; set; }
        public string REASON { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_EmployeeSalary> TB_EmployeeSalary { get; set; }
    }
}
