//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EmployeeSalary
    {
        public int SALARY_ID { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public Nullable<decimal> BASIC_SALARY { get; set; }
        public string SALARY_FOR_MONTH { get; set; }
        public Nullable<int> SALARY_FOR_YEAR { get; set; }
        public Nullable<System.DateTime> SALARY_DATE { get; set; }
        public Nullable<byte> PRESENT_DAYS { get; set; }
        public Nullable<decimal> ADVANCE_SALARY { get; set; }
        public Nullable<long> EMP_LOAN_ID { get; set; }
        public Nullable<decimal> LOAN_INSTALLMENT { get; set; }
        public Nullable<decimal> CURRENT_MOBILE_BILL { get; set; }
        public Nullable<decimal> EXTRA_MOBILE_BILL { get; set; }
        public Nullable<decimal> INCENTIVE_AMOUNT { get; set; }
        public Nullable<decimal> BONUS_DETAILS_TOTAL_SALARY { get; set; }
        public Nullable<byte> BONUS_PERCENTAGE { get; set; }
        public Nullable<decimal> SALARY_BONUS { get; set; }
        public Nullable<bool> IS_SALARY_HOLD { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<long> COMPANY_BANK_ID { get; set; }
        public Nullable<long> NET_SALARY { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> GROSS_SALARY { get; set; }
        public Nullable<long> TOTAL_SALARY { get; set; }
        public string IsSalaryTransferred { get; set; }
    
        public virtual TB_EmployeeLoan TB_EmployeeLoan { get; set; }
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
    }
}
