//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EmployeeTask
    {
        public int EmployeeTaskID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string EmployeeType { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string AllocatedWork { get; set; }
        public string WorkResult { get; set; }
        public string Remark { get; set; }
        public string NewLearning { get; set; }
        public string Reasons { get; set; }
        public string TaskStatus { get; set; }
        public string Note { get; set; }
        public string Type { get; set; }
        public string EquipmentsPartDetails { get; set; }
        public Nullable<System.DateTime> InTime { get; set; }
        public Nullable<System.DateTime> OutTime { get; set; }
        public string PersonFrom { get; set; }
        public string PersonName { get; set; }
        public string WhoAskForIt { get; set; }
        public string Purpose { get; set; }
        public string DCNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
    }
}
