//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EmployeeTaskMaster
    {
        public int TaskId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public string TaskTitle { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public string HospitalName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
    
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
    }
}
