//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_FirmMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_FirmMaster()
        {
            this.Tb_AMC_CMC_Master = new HashSet<Tb_AMC_CMC_Master>();
            this.TB_DeliveryChallan = new HashSet<TB_DeliveryChallan>();
            this.Tb_PaymentReceiptMaster = new HashSet<Tb_PaymentReceiptMaster>();
            this.TB_ServiceCall = new HashSet<TB_ServiceCall>();
            this.TB_InvoiceMaster = new HashSet<TB_InvoiceMaster>();
            this.TB_InvoiceMaster1 = new HashSet<TB_InvoiceMaster>();
        }
    
        public long F_ID { get; set; }
        public Nullable<long> CUSTOMER_ID { get; set; }
        public string FIRM_NAME { get; set; }
        public Nullable<long> CUSTOMER_TYPE_ID { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_AMC_CMC_Master> Tb_AMC_CMC_Master { get; set; }
        public virtual Tb_CustomerMaster Tb_CustomerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DeliveryChallan> TB_DeliveryChallan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_PaymentReceiptMaster> Tb_PaymentReceiptMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ServiceCall> TB_ServiceCall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_InvoiceMaster> TB_InvoiceMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_InvoiceMaster> TB_InvoiceMaster1 { get; set; }
    }
}
