//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_IncentiveScheme
    {
        public int IS_ID { get; set; }
        public string SERIAL_NO { get; set; }
        public string REF_NO { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public Nullable<System.DateTime> INCENTIVE_DATE { get; set; }
        public Nullable<byte> INC_TYPE_ID { get; set; }
        public Nullable<byte> INC_SERVICE_TYPE_ID { get; set; }
        public Nullable<decimal> INCENTIVE_AMOUNT { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
        public virtual TB_IncentiveServiceType TB_IncentiveServiceType { get; set; }
        public virtual TB_IncentiveType TB_IncentiveType { get; set; }
    }
}
