//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_InvoiceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_InvoiceMaster()
        {
            this.TB_Invoice_Accessories = new HashSet<TB_Invoice_Accessories>();
            this.TB_Invoice_MedtronicAccessories = new HashSet<TB_Invoice_MedtronicAccessories>();
            this.TB_Invoice_SparePart = new HashSet<TB_Invoice_SparePart>();
            this.TB_SparePartStock = new HashSet<TB_SparePartStock>();
            this.TB_ProductStockMaster = new HashSet<TB_ProductStockMaster>();
        }
    
        public int INVOICE_ID { get; set; }
        public string INVOICE_NUMBER { get; set; }
        public string DC_NUMBER { get; set; }
        public Nullable<long> Customer_ID { get; set; }
        public Nullable<System.DateTime> INVOICE_DATE { get; set; }
        public Nullable<long> P_ID { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string SERIAL_NO { get; set; }
        public string HSN_CODE { get; set; }
        public Nullable<bool> IS_INVOICE_FOR_SPAREPARTS { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<bool> INC_ALL_TAXES { get; set; }
        public Nullable<byte> GST { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<decimal> AMOUNT_INC_TAX { get; set; }
        public Nullable<decimal> OTHER_SERVICES_AMOUNT { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public string COMMENTS { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<long> F_ID { get; set; }
        public string PNDT_ACKNOWLEDGEMENT_IMAGE { get; set; }
        public string PNDT_CERTIFICATE_IMAGE { get; set; }
        public string ADMIN_REMARK { get; set; }
        public Nullable<long> PNDT_UPLOADED_BY_ADMIN { get; set; }
        public string DISPATCHED_THROUGH { get; set; }
        public string DESTINATION { get; set; }
        public string SERIAL_NO_OF_TUBE { get; set; }
        public Nullable<int> NO_OF_TRANSDUCER { get; set; }
        public string SOFTWARE_VERSION { get; set; }
        public string WARRANTY_IN_DMY { get; set; }
        public Nullable<decimal> WARRANTY_PERIOD { get; set; }
        public string PI_NUMBER { get; set; }
        public Nullable<long> BANK_ID { get; set; }
        public string PAYMENT_TERMS_DETAILS { get; set; }
        public Nullable<System.DateTime> WARRANTY_FROM { get; set; }
        public Nullable<System.DateTime> WARRANTY_TO { get; set; }
        public string PO_NUMBER { get; set; }
        public string PNDT_NO { get; set; }
        public string PNDT_ACK_NO { get; set; }
        public Nullable<System.DateTime> INSTALLATION_DATE { get; set; }
        public string CHALLAN_IMAGE { get; set; }
        public Nullable<long> CHALLAN_UPLOADED_BY_ADMIN { get; set; }
        public string INSTALLATION_REPORT_IMAGE { get; set; }
        public Nullable<long> INSTALLATION_REPORT_UPLOADED_BY { get; set; }
        public string BATCH_NO { get; set; }
    
        public virtual Tb_CustomerMaster Tb_CustomerMaster { get; set; }
        public virtual Tb_CustomerMaster Tb_CustomerMaster1 { get; set; }
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster1 { get; set; }
        public virtual Tb_FirmMaster Tb_FirmMaster { get; set; }
        public virtual Tb_FirmMaster Tb_FirmMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Invoice_Accessories> TB_Invoice_Accessories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Invoice_MedtronicAccessories> TB_Invoice_MedtronicAccessories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Invoice_SparePart> TB_Invoice_SparePart { get; set; }
        public virtual Tb_Product Tb_Product { get; set; }
        public virtual Tb_Product Tb_Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SparePartStock> TB_SparePartStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ProductStockMaster> TB_ProductStockMaster { get; set; }
    }
}
