//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_IncentiveMaster
    {
        public int IM_ID { get; set; }
        public Nullable<byte> INC_SERVICE_TYPE_ID { get; set; }
        public Nullable<decimal> INCENTIVE_AMOUNT { get; set; }
        public string UNIT { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    
        public virtual TB_IncentiveServiceType TB_IncentiveServiceType { get; set; }
    }
}
