//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Invoice_Accessories
    {
        public int INVOICE_ACCESSORIES_ID { get; set; }
        public Nullable<int> INVOICE_ID { get; set; }
        public Nullable<long> STD_ID { get; set; }
        public Nullable<int> PART_QTY { get; set; }
        public Nullable<decimal> PART_PRICE { get; set; }
        public string HSN_CODE { get; set; }
        public string SERIAL_NO { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string BATCH_NO { get; set; }
    
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
        public virtual TB_InvoiceMaster TB_InvoiceMaster { get; set; }
        public virtual Tb_StdAccessoriesMaster Tb_StdAccessoriesMaster { get; set; }
    }
}
