//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Leads
    {
        public long DSR_LEAD_ID { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<System.DateTime> DSR_DATE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string FIRM_NAME { get; set; }
        public string FIRM_ADDRESS { get; set; }
        public string CITY_NAME { get; set; }
        public string MOBILE_NO { get; set; }
        public string MODALITY { get; set; }
        public string EMAIL_ID { get; set; }
        public string PROJECHTED_MODEL { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public string CUSTOMER_REQUIREMENT { get; set; }
        public string SALES_PERSON_COMMITMENTS { get; set; }
        public string FORCASTED_MONTH { get; set; }
        public Nullable<double> PRICE { get; set; }
        public Nullable<long> BUY_PERCENT { get; set; }
        public string ENQUIRY_TYPE { get; set; }
        public string UPLOAD_VISITING_CARD { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    }
}
