//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_MindrayQuotationMaster
    {
        public long MQ_ID { get; set; }
        public string QUOTATION_TYPE { get; set; }
        public string QUOTATION_NO { get; set; }
        public Nullable<long> CUSTOMER_ID { get; set; }
        public Nullable<long> FIRM_ID { get; set; }
        public Nullable<System.DateTime> QUOTATION_DATE { get; set; }
        public string PNDT_STATUS { get; set; }
        public string PNDT_NO { get; set; }
        public Nullable<System.DateTime> PO_DATE { get; set; }
        public string PAYMENT_TERM { get; set; }
        public string NOTE { get; set; }
        public string SELECT_PRODUCT_IS_NEW { get; set; }
        public Nullable<long> MP_ID { get; set; }
        public string QUOTATION_FOR_SPARE_PART { get; set; }
        public string QUANTITY { get; set; }
        public string PRODUCT_PRICE { get; set; }
        public string MODIFY_PRODUCT_PRICE { get; set; }
        public Nullable<long> CUSTOMER_TYPE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string WARRANTY_IN_DMY { get; set; }
        public Nullable<int> WARRANTY_PERIOD { get; set; }
        public Nullable<decimal> AMOUNT_WITHOUT_TAX { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<decimal> AMOUNT_WITH_TAX { get; set; }
        public Nullable<int> TAX_PERCENTAGE { get; set; }
        public Nullable<bool> AMOUNT_INC_TAX { get; set; }
        public string PAYMENT_TERM_DETAILS { get; set; }
        public string PURCHASE_ORDER_NO { get; set; }
        public string AERB_OR_PNDT { get; set; }
        public Nullable<long> BANK_ID { get; set; }
        public Nullable<bool> IS_SPL_WARRANTY { get; set; }
    
        public virtual Tb_MindrayProduct Tb_MindrayProduct { get; set; }
    }
}
