//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MedtronicQuotationProductAccessories
    {
        public int MQPA_ID { get; set; }
        public Nullable<long> Q_ID { get; set; }
        public Nullable<int> MED_ACC_ID { get; set; }
        public Nullable<byte> QUANTITY { get; set; }
        public Nullable<decimal> BASIC_PRICE { get; set; }
        public Nullable<byte> GST_PERCENTAGE { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> DISCOUNT { get; set; }
        public Nullable<decimal> PART_TOTAL_AMOUNT { get; set; }
    
        public virtual TB_MedtronicAccessories TB_MedtronicAccessories { get; set; }
        public virtual Tb_QuotationMaster Tb_QuotationMaster { get; set; }
    }
}
