//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MedtronicAccessories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_MedtronicAccessories()
        {
            this.TB_AMC_MedtronicAccessories = new HashSet<TB_AMC_MedtronicAccessories>();
            this.TB_MedtronicQuotationProductAccessories = new HashSet<TB_MedtronicQuotationProductAccessories>();
            this.TB_ServiceCall = new HashSet<TB_ServiceCall>();
            this.TB_DC_MedtronicAccessories = new HashSet<TB_DC_MedtronicAccessories>();
            this.TB_Invoice_MedtronicAccessories = new HashSet<TB_Invoice_MedtronicAccessories>();
        }
    
        public int MED_ACC_ID { get; set; }
        public Nullable<byte> MED_ACCESSORY_TYPE_ID { get; set; }
        public Nullable<long> P_ID { get; set; }
        public string ACCESSORY_CODE { get; set; }
        public string ACCESSORY_NAME { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> BASIC_PRICE { get; set; }
        public Nullable<byte> GST_PERCENTAGE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string HSN_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_AMC_MedtronicAccessories> TB_AMC_MedtronicAccessories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MedtronicQuotationProductAccessories> TB_MedtronicQuotationProductAccessories { get; set; }
        public virtual TB_MedtronicAccessoriesType TB_MedtronicAccessoriesType { get; set; }
        public virtual Tb_Product Tb_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ServiceCall> TB_ServiceCall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DC_MedtronicAccessories> TB_DC_MedtronicAccessories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Invoice_MedtronicAccessories> TB_Invoice_MedtronicAccessories { get; set; }
    }
}
