//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_MindrayProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_MindrayProduct()
        {
            this.Tb_MindrayQuotationMaster = new HashSet<Tb_MindrayQuotationMaster>();
            this.Tb_ProbeSpecificationsPart = new HashSet<Tb_ProbeSpecificationsPart>();
        }
    
        public long MP_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONFIGURATION { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string PRODUCT_IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_MindrayQuotationMaster> Tb_MindrayQuotationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ProbeSpecificationsPart> Tb_ProbeSpecificationsPart { get; set; }
    }
}
