//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_MindrayQuotationProductDetails
    {
        public long QUOTATION_ID { get; set; }
        public Nullable<long> MQ_ID { get; set; }
        public Nullable<long> CUSTOMER_ID { get; set; }
        public Nullable<long> CUSTOMER_TYPE_ID { get; set; }
        public Nullable<long> PRODUCT_ID { get; set; }
        public string PRODUCT_QUANTITY { get; set; }
        public string PROCUCT_PRICE { get; set; }
        public Nullable<bool> IS_WITH_PROBE_ACC { get; set; }
        public string PROBE_ID_LIST { get; set; }
        public string PROBE_QUANTITY_LIST { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string PROBEPART_PRICE_LIST { get; set; }
    }
}
