//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Notification
    {
        public long NOTE_ID { get; set; }
        public string TITLE { get; set; }
        public string SEND_MESSAGE { get; set; }
        public string IMAGE { get; set; }
        public string ISVIEW { get; set; }
        public Nullable<long> UNSEEN_COUNT { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    }
}
