//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_PaymentReceiptMaster
    {
        public long R_ID { get; set; }
        public string PAYMENT_RECEIPT_NO { get; set; }
        public Nullable<long> CUSTOMER_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public long FIRM_ID { get; set; }
        public string FIRM_NAME { get; set; }
        public string PAYMENT_REF_NO { get; set; }
        public string PAYMENT_RECEIPT_TYPE { get; set; }
        public string PAYMENT_TYPE { get; set; }
        public string RECIEPT_FOR { get; set; }
        public decimal PAYMENT_AMOUNT { get; set; }
        public decimal AMOUNT_RECEIVED { get; set; }
        public decimal AMOUNT_REMAINING { get; set; }
        public string STATUS { get; set; }
        public System.DateTime RECEIPT_GEN_DATE { get; set; }
        public string TXN_ID { get; set; }
        public Nullable<long> Q_ID { get; set; }
    
        public virtual Tb_FirmMaster Tb_FirmMaster { get; set; }
        public virtual Tb_QuotationMaster Tb_QuotationMaster { get; set; }
    }
}
