//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Product()
        {
            this.Tb_AMC_CMC_Master = new HashSet<Tb_AMC_CMC_Master>();
            this.TB_DeliveryChallan = new HashSet<TB_DeliveryChallan>();
            this.TB_MedtronicAccessories = new HashSet<TB_MedtronicAccessories>();
            this.TB_SolutionBank = new HashSet<TB_SolutionBank>();
            this.Tb_QuotationMaster = new HashSet<Tb_QuotationMaster>();
            this.TB_ServiceCall = new HashSet<TB_ServiceCall>();
            this.Tb_StdAccessoriesMaster = new HashSet<Tb_StdAccessoriesMaster>();
            this.TB_InvoiceMaster = new HashSet<TB_InvoiceMaster>();
            this.TB_InvoiceMaster1 = new HashSet<TB_InvoiceMaster>();
            this.TB_Vendor_PO_Products = new HashSet<TB_Vendor_PO_Products>();
            this.TB_SparePartStock = new HashSet<TB_SparePartStock>();
            this.TB_ProductStockMaster = new HashSet<TB_ProductStockMaster>();
        }
    
        public long P_ID { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public Nullable<long> CAT_ID { get; set; }
        public Nullable<long> M_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string LETTER_REF_NO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<byte> PT_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string CONFIGURATION { get; set; }
        public string PRODUCT_IMAGE { get; set; }
        public string PRODUCT_CODE { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> BASIC_PRICE { get; set; }
        public Nullable<byte> GST_PERCENTAGE { get; set; }
        public string HSN_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_AMC_CMC_Master> Tb_AMC_CMC_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DeliveryChallan> TB_DeliveryChallan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MedtronicAccessories> TB_MedtronicAccessories { get; set; }
        public virtual TB_ProductType TB_ProductType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SolutionBank> TB_SolutionBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_QuotationMaster> Tb_QuotationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ServiceCall> TB_ServiceCall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_StdAccessoriesMaster> Tb_StdAccessoriesMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_InvoiceMaster> TB_InvoiceMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_InvoiceMaster> TB_InvoiceMaster1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Vendor_PO_Products> TB_Vendor_PO_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SparePartStock> TB_SparePartStock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ProductStockMaster> TB_ProductStockMaster { get; set; }
    }
}
