//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ProductStockMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ProductStockMaster()
        {
            this.TB_SparePartStock = new HashSet<TB_SparePartStock>();
        }
    
        public long P_STOCK_ID { get; set; }
        public string P_STOCK_NO { get; set; }
        public Nullable<System.DateTime> STOCK_ENTRY_DATE { get; set; }
        public Nullable<long> P_ID { get; set; }
        public Nullable<int> P_QTY { get; set; }
        public string P_SERIAL_NO { get; set; }
        public Nullable<bool> IS_URD_SUPPLIER { get; set; }
        public Nullable<long> URD_SUPPLIER_ID { get; set; }
        public Nullable<long> VENDOR_SUPPLIER_ID { get; set; }
        public string HSN_CODE { get; set; }
        public string DEPART_FROM { get; set; }
        public string INVOICE_NO { get; set; }
        public string DC_NO { get; set; }
        public string ARRIVE_AT { get; set; }
        public string VEHICAL_NO { get; set; }
        public Nullable<System.DateTime> MATERIAL_RECEIVED_DATE { get; set; }
        public string COMMENTS { get; set; }
        public string SHIPMENT_DETAILS { get; set; }
        public Nullable<long> EMPLOYEE_ID { get; set; }
        public Nullable<int> PENDING_QTY { get; set; }
        public Nullable<int> INVOICE_ID { get; set; }
        public Nullable<long> ASSIGN_TO { get; set; }
        public Nullable<System.DateTime> ASSIGN_ON_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string PRODUCT_TYPE { get; set; }
    
        public virtual Tb_CustomerMaster Tb_CustomerMaster { get; set; }
        public virtual Tb_CustomerMaster Tb_CustomerMaster1 { get; set; }
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
        public virtual TB_InvoiceMaster TB_InvoiceMaster { get; set; }
        public virtual Tb_Product Tb_Product { get; set; }
        public virtual Tb_VendorRegistration Tb_VendorRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SparePartStock> TB_SparePartStock { get; set; }
    }
}
