//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ProbeSpecificationsPart
    {
        public long PS_ID { get; set; }
        public Nullable<long> MP_ID { get; set; }
        public string PROBE_NAME { get; set; }
        public string PRICE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    
        public virtual Tb_MindrayProduct Tb_MindrayProduct { get; set; }
    }
}
