//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ServiceCall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ServiceCall()
        {
            this.TB_ServiceCallAssignHistory = new HashSet<TB_ServiceCallAssignHistory>();
            this.TB_SolutionBank = new HashSet<TB_SolutionBank>();
        }
    
        public long SERVICE_CALL_ID { get; set; }
        public string SERVICE_CALL_NUMBER { get; set; }
        public Nullable<long> CUSTOMER_ID { get; set; }
        public Nullable<long> F_ID { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> CALL_ASSIGN_DATE { get; set; }
        public Nullable<System.DateTime> SCHEDULE_CALL_DATE { get; set; }
        public Nullable<long> P_ID { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public Nullable<byte> CONTRACT_TYPE_ID { get; set; }
        public Nullable<byte> SERVICE_TYPE_ID { get; set; }
        public Nullable<byte> CALL_PRIORITY_TYPE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> ASSIGN_CALL_BY_ID { get; set; }
        public string CALL_STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<int> MED_ACC_ID { get; set; }
        public string SERVICE_FOR { get; set; }
        public string ASSIGN_STATUS { get; set; }
        public string WORK_STATUS { get; set; }
        public string SERVICE_REMARK { get; set; }
        public string UPLOAD_SERVICE_REPORT_DOC { get; set; }
        public Nullable<long> BANK_ID { get; set; }
        public string LATITUDE { get; set; }
        public string LONGITUDE { get; set; }
    
        public virtual Tb_CustomerMaster Tb_CustomerMaster { get; set; }
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster1 { get; set; }
        public virtual Tb_FirmMaster Tb_FirmMaster { get; set; }
        public virtual Tb_Product Tb_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ServiceCallAssignHistory> TB_ServiceCallAssignHistory { get; set; }
        public virtual TB_ServiceCall TB_ServiceCall1 { get; set; }
        public virtual TB_ServiceCall TB_ServiceCall2 { get; set; }
        public virtual TB_MedtronicAccessories TB_MedtronicAccessories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_SolutionBank> TB_SolutionBank { get; set; }
        public virtual TB_CompanyBankMaster TB_CompanyBankMaster { get; set; }
    }
}
