//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_SparePart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_SparePart()
        {
            this.TB_DC_SparePart = new HashSet<TB_DC_SparePart>();
            this.TB_Invoice_SparePart = new HashSet<TB_Invoice_SparePart>();
        }
    
        public long SP_ID { get; set; }
        public Nullable<long> CAT_ID { get; set; }
        public Nullable<long> M_ID { get; set; }
        public Nullable<long> P_ID { get; set; }
        public string SPARE_PART { get; set; }
        public string PRICE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string HSN_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DC_SparePart> TB_DC_SparePart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Invoice_SparePart> TB_Invoice_SparePart { get; set; }
    }
}
