//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SolutionBank
    {
        public int SB_ID { get; set; }
        public Nullable<long> P_ID { get; set; }
        public Nullable<long> SERVICE_ENGG_ID { get; set; }
        public string PROBLEM_DESCRIPTION { get; set; }
        public string SOLUTION_DESCRIPTION { get; set; }
        public Nullable<long> SOLUTION_PROVIDER_ID { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<long> SERVICE_CALL_ID { get; set; }
    
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster1 { get; set; }
        public virtual Tb_Product Tb_Product { get; set; }
        public virtual TB_ServiceCall TB_ServiceCall { get; set; }
    }
}
