//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_SparePartStock
    {
        public long SP_STOCK_ID { get; set; }
        public string SP_STOCK_NO { get; set; }
        public Nullable<System.DateTime> STOCK_ENTRY_DATE { get; set; }
        public Nullable<long> P_ID { get; set; }
        public Nullable<int> PART_TYPE_ID { get; set; }
        public Nullable<long> PART_ID { get; set; }
        public Nullable<int> PART_QTY { get; set; }
        public string PART_SERIAL_NO { get; set; }
        public string PART_NO { get; set; }
        public Nullable<decimal> PART_PRICE { get; set; }
        public string HSN_CODE { get; set; }
        public string LOCATION { get; set; }
        public string REMARK { get; set; }
        public Nullable<int> PENDING_QTY { get; set; }
        public Nullable<int> INVOICE_ID { get; set; }
        public Nullable<long> ASSIGN_TO { get; set; }
        public Nullable<System.DateTime> ASSIGN_ON_DATE { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string PRODUCT_TYPE { get; set; }
        public string BATCH_NO { get; set; }
        public Nullable<long> P_STOCK_ID { get; set; }
    
        public virtual Tb_CustomerMaster Tb_CustomerMaster { get; set; }
        public virtual TB_InvoiceMaster TB_InvoiceMaster { get; set; }
        public virtual TB_PartType TB_PartType { get; set; }
        public virtual Tb_Product Tb_Product { get; set; }
        public virtual TB_ProductStockMaster TB_ProductStockMaster { get; set; }
    }
}
