//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_URDProduct
    {
        public long UP_ID { get; set; }
        public string LETER_REF_NO { get; set; }
        public Nullable<System.DateTime> LETTER_DATE { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> CUSTOMER_ID { get; set; }
        public Nullable<long> FIRM_ID { get; set; }
        public string URD_STATUS { get; set; }
        public Nullable<long> CAT_ID { get; set; }
        public Nullable<long> M_ID { get; set; }
        public Nullable<long> P_ID { get; set; }
        public string MRC_NO { get; set; }
        public string PNDT_CELL { get; set; }
        public string PNDT_CIRTIFICATE_NO { get; set; }
        public Nullable<System.DateTime> VALIDITY_DATE { get; set; }
        public string GOV_PERMITED_URD_REF_NO { get; set; }
        public Nullable<long> EMP_ENG_ID { get; set; }
        public Nullable<System.DateTime> LETTER_RECIVED_DATE { get; set; }
        public string ACCESSORIES_DETAILS { get; set; }
        public string UPLOD_GOV_PERMISSION_LATER { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string SERIAL_NO { get; set; }
        public string COMPANY_PNDT_NO { get; set; }
        public string COMPANY_PNDT_CERTIFICATE { get; set; }
    }
}
