//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Vendor_PO_AccessoriesAndSpareParts
    {
        public long VPO_ACC_ID { get; set; }
        public Nullable<long> ACC_ID { get; set; }
        public Nullable<long> VPO_ID { get; set; }
        public Nullable<int> ACC_TYPE_ID { get; set; }
        public Nullable<long> VPO_P_ID { get; set; }
        public Nullable<int> PART_QTY { get; set; }
        public Nullable<decimal> PART_PRICE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    
        public virtual TB_VendorAccType TB_VendorAccType { get; set; }
        public virtual TB_Vendor_PO_Master TB_Vendor_PO_Master { get; set; }
        public virtual TB_Vendor_PO_Products TB_Vendor_PO_Products { get; set; }
    }
}
