//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Vendor_PO_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Vendor_PO_Master()
        {
            this.TB_Vendor_PO_AccessoriesAndSpareParts = new HashSet<TB_Vendor_PO_AccessoriesAndSpareParts>();
            this.TB_Vendor_PO_Products = new HashSet<TB_Vendor_PO_Products>();
        }
    
        public long VPO_ID { get; set; }
        public string VPO_NUMBER { get; set; }
        public Nullable<System.DateTime> VPO_DATE { get; set; }
        public Nullable<long> VENDOR_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public Nullable<long> ADMIN_ID { get; set; }
        public Nullable<int> CUSTOMER_TYPE_ID { get; set; }
        public string TERMS_AND_CONDITION { get; set; }
        public Nullable<bool> INC_ALL_TAXES { get; set; }
        public Nullable<byte> GST { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<decimal> TAX_AMOUNT { get; set; }
        public Nullable<decimal> AMOUNT_INC_TAX { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
    
        public virtual TB_CompanyMaster TB_CompanyMaster { get; set; }
        public virtual Tb_EmployeeMaster Tb_EmployeeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Vendor_PO_AccessoriesAndSpareParts> TB_Vendor_PO_AccessoriesAndSpareParts { get; set; }
        public virtual Tb_VendorRegistration Tb_VendorRegistration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Vendor_PO_Products> TB_Vendor_PO_Products { get; set; }
    }
}
