//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Vendor_PO_Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Vendor_PO_Products()
        {
            this.TB_Vendor_PO_AccessoriesAndSpareParts = new HashSet<TB_Vendor_PO_AccessoriesAndSpareParts>();
        }
    
        public long VPO_P_ID { get; set; }
        public Nullable<long> VPO_ID { get; set; }
        public Nullable<long> P_ID { get; set; }
        public Nullable<bool> IS_WITH_WARRANTY { get; set; }
        public Nullable<int> WARRANTY_QTY { get; set; }
        public Nullable<decimal> WARRANTY_PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<long> VENDOR_ID { get; set; }
    
        public virtual Tb_Product Tb_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Vendor_PO_AccessoriesAndSpareParts> TB_Vendor_PO_AccessoriesAndSpareParts { get; set; }
        public virtual TB_Vendor_PO_Master TB_Vendor_PO_Master { get; set; }
        public virtual Tb_VendorRegistration Tb_VendorRegistration { get; set; }
    }
}
