//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sai_Helth_care
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_VendorRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_VendorRegistration()
        {
            this.TB_Vendor_PO_Master = new HashSet<TB_Vendor_PO_Master>();
            this.TB_Vendor_PO_Products = new HashSet<TB_Vendor_PO_Products>();
            this.TB_ProductStockMaster = new HashSet<TB_ProductStockMaster>();
        }
    
        public long V_ID { get; set; }
        public Nullable<long> COMPANY_ID { get; set; }
        public string VENDOR_NAME { get; set; }
        public string CONTACT_NO { get; set; }
        public string ALTERNATE_CONTACT_NO { get; set; }
        public string EMAIL { get; set; }
        public string ALTERNATE_EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<long> STATE_ID { get; set; }
        public Nullable<long> CITY_ID { get; set; }
        public string ZIP_CODE { get; set; }
        public string PAN_CARD_NO { get; set; }
        public string GST_NO { get; set; }
        public string TIN_NO { get; set; }
        public string STATUS { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public string VENDOR_COMPANY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Vendor_PO_Master> TB_Vendor_PO_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Vendor_PO_Products> TB_Vendor_PO_Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ProductStockMaster> TB_ProductStockMaster { get; set; }
    }
}
